services:
  auth:
    image: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: dev
    command: pnpm run start:dev auth
    ports:
      - '8080:8080'
    env_file:
      - .dev.env
    volumes:
      - .:/app
    depends_on:
      - postgres

  slack:
    image: slack
    build:
      context: .
      dockerfile: ./apps/slack.management/Dockerfile
      target: dev

    command: pnpm run start:dev slack.management
    ports:
      - '8082:8082'
    volumes:
      - .:/app
    env_file:
      - .dev.env
    depends_on:
      - auth
      - postgres

  social-network:
    image: social-network
    build:
      context: .
      dockerfile: ./apps/social.network.management/Dockerfile
      target: dev
    command: pnpm run start:dev social.network.management
    ports:
      - '8084:8084'
    volumes:
      - .:/app
    env_file:
      - .dev.env
    depends_on:
      - auth
      - postgres

  realtime:
    image: realtime
    build:
      context: .
      dockerfile: ./apps/realtime-ws/Dockerfile
      target: dev
    command: pnpm run start:dev realtime-ws
    ports:
      - '8086:8086'
      - '3001:3001' # For dms
    volumes:
      - .:/app
    env_file:
      - .dev.env
    depends_on:
      - auth
      - postgres
      - slack
      - social-network

  test:
    image: test
    build:
      context: .
      dockerfile: ./apps/test/Dockerfile
      target: dev
    command: pnpm run start:dev test
    ports:
      - '4040:4040'
    volumes:
      - .:/app
    depends_on:
      - auth

  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .dev.env
    ports:
      - '5434:5434'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    command: >
      bash -c "
        mkdir -p /var/log/pgadmin
        exec /entrypoint.sh 2>/dev/null
      "
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    restart: always
    ports:
      - '5050:80'
    env_file:
      - .dev.env
    depends_on:
      - postgres
volumes:
  postgres_data:
